<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Employees.BusinessLogic\Employees.BusinessLogic.csproj" />
    <ProjectReference Include="..\Employees.DataAccessLayer\Employees.DataAccessLayer.csproj" />
    <ProjectReference Include="..\Employees.Model\Employees.Model.csproj" />
  </ItemGroup>

</Project>